import React, { useState, useEffect } from 'react';
import '../../styles/carrier/AddLoads.css';
import { API_URL } from '../../config';
import { auth } from '../../firebase';
import Geocoder from '../common/Geocoder';
import RouteMap from '../common/RouteMap';
import { useTr } from '../../i18n/useTr';

export default function AddLoads({ onClose, draftLoad, isShipper = false }) {
  const { language, tr } = useTr();
  const locale = language === 'Spanish' ? 'es-ES' : language === 'Arabic' ? 'ar' : 'en-US';
  const fmtMoney = (amt) => {
    const n = Number(amt || 0);
    try {
      return new Intl.NumberFormat(locale, { style: 'currency', currency: 'USD' }).format(n);
    } catch {
      return `$${n.toFixed(2)}`;
    }
  };

  const [step, setStep] = useState(1);
  const [chargeName, setChargeName] = useState('');
  const [chargeAmount, setChargeAmount] = useState('');
  const [advancedCharges, setAdvancedCharges] = useState([]); // [{"name": "Detention", "amount": 150}]
  const [loadId, setLoadId] = useState(null); // Will be generated by backend
  const [estimatedDistance, setEstimatedDistance] = useState(null);
  const [estimatedTransitTime, setEstimatedTransitTime] = useState(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);
  const [matchedCarriers, setMatchedCarriers] = useState([]);
  
  // Additional routes state
  const [additionalRoutes, setAdditionalRoutes] = useState([]); // [{location, type, date}]
  const [showAddRoute, setShowAddRoute] = useState(false);
  const [newRouteLocation, setNewRouteLocation] = useState('');
  const [newRouteType, setNewRouteType] = useState('pickup');
  const [newRouteDate, setNewRouteDate] = useState('');
  
  const [formData, setFormData] = useState({
    // Step 1: Route & Equipment
    origin: '',
    destination: '',
    pickupDate: '',
    deliveryDate: '',
    pickupAppointmentType: 'FCFS', // FCFS or BY_APPOINTMENT
    deliveryAppointmentType: 'FCFS',
    equipmentType: 'Dry Van', // Backend enum format
    loadType: 'FTL', // FTL, LTL, PARTIAL
    weight: '',
    palletCount: '',
    
    // Step 2: Price & Details
    rateType: 'flatRate', // flatRate, perMile, hourly
    linehaul: '',
    fuelSurcharge: '',
    commodity: '',
    specialRequirements: [], // Array of strings
    paymentTerms: 'Quick Pay', // Quick Pay, 15 Days, 30 Days, Custom
    notes: '',
    
    // Step 3: Visibility & Preferences
    visibility: 'public', // public, network, private
    selectedCarriers: [], // For PRIVATE visibility
    autoMatch: true,
    instantBooking: false, // Allow carriers to book without approval
    autoPostToFreightpower: true,
    autoPostToTruckstop: false,
    autoPostTo123loadboard: false,
    notifyOnCarrierViews: true,
    notifyOnOfferReceived: true,
    notifyOnLoadCovered: true,
  });

  // Shipper posting: keep visibility strictly public.
  useEffect(() => {
    if (!isShipper) return;
    setFormData(prev => ({
      ...prev,
      visibility: 'public',
      selectedCarriers: [],
    }));
  }, [isShipper]);

  // Pre-populate form if resuming a draft load
  useEffect(() => {
    if (draftLoad) {
      setLoadId(draftLoad.load_id);
      
      // Set estimated values from draft
      if (draftLoad.estimated_distance) {
        setEstimatedDistance(draftLoad.estimated_distance);
      }
      if (draftLoad.estimated_transit_time) {
        setEstimatedTransitTime(draftLoad.estimated_transit_time);
      }
      
      // Set additional routes if present
      if (draftLoad.additional_routes && Array.isArray(draftLoad.additional_routes)) {
        setAdditionalRoutes(draftLoad.additional_routes);
      }
      
      const nextFormData = {
        // Step 1
        origin: draftLoad.origin || '',
        destination: draftLoad.destination || '',
        pickupDate: draftLoad.pickup_date || '',
        deliveryDate: draftLoad.delivery_date || '',
        pickupAppointmentType: draftLoad.pickup_appointment_type || 'FCFS',
        deliveryAppointmentType: draftLoad.delivery_appointment_type || 'FCFS',
        equipmentType: draftLoad.equipment_type || 'Dry Van',
        loadType: draftLoad.load_type || 'FTL',
        weight: draftLoad.weight || '',
        palletCount: draftLoad.pallet_count || '',
        
        // Step 2
        rateType: draftLoad.rate_type === 'Flat Rate' ? 'flatRate' : draftLoad.rate_type === 'Per Mile' ? 'perMile' : 'hourly',
        linehaul: draftLoad.linehaul_rate || '',
        fuelSurcharge: draftLoad.fuel_surcharge || '',
        commodity: draftLoad.commodity || '',
        specialRequirements: draftLoad.special_requirements || [],
        paymentTerms: draftLoad.payment_terms || 'Quick Pay',
        notes: draftLoad.notes || '',
        
        // Step 3
        visibility: draftLoad.visibility?.toLowerCase() || 'public',
        selectedCarriers: draftLoad.selected_carriers || [],
        autoMatch: draftLoad.auto_match_ai !== undefined ? draftLoad.auto_match_ai : true,
        instantBooking: draftLoad.instant_booking || false,
        autoPostToFreightpower: draftLoad.auto_post_to_freightpower !== undefined ? draftLoad.auto_post_to_freightpower : true,
        autoPostToTruckstop: draftLoad.auto_post_to_truckstop || false,
        autoPostTo123loadboard: draftLoad.auto_post_to_123loadboard || false,
        notifyOnCarrierViews: draftLoad.notify_on_carrier_views !== undefined ? draftLoad.notify_on_carrier_views : true,
        notifyOnOfferReceived: draftLoad.notify_on_offer_received !== undefined ? draftLoad.notify_on_offer_received : true,
        notifyOnLoadCovered: draftLoad.notify_on_load_covered !== undefined ? draftLoad.notify_on_load_covered : true,
      };

      // Shipper posting: keep visibility strictly public.
      setFormData(isShipper ? { ...nextFormData, visibility: 'public', selectedCarriers: [] } : nextFormData);
      
      // Set advanced charges if present
      if (draftLoad.advanced_charges && Array.isArray(draftLoad.advanced_charges)) {
        setAdvancedCharges(draftLoad.advanced_charges);
      }
      
      // Determine which step to start at based on what's complete
      if (draftLoad.linehaul_rate) {
        setStep(3); // Has pricing, go to Step 3
      } else if (draftLoad.origin && draftLoad.destination) {
        setStep(2); // Has route, go to Step 2
      }
    }
  }, [draftLoad, isShipper]);

  const handleInputChange = (e) => {
    const { name, value, type, checked } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }));
  };

  const handleLoadTypeSelect = (type) => {
    setFormData(prev => ({ ...prev, loadType: type }));
  };

  const handleVisibilitySelect = (option) => {
    if (isShipper) return;
    setFormData(prev => ({ ...prev, visibility: option }));
  };

  const toggleRequirement = (req) => {
    setFormData(prev => ({
      ...prev,
      specialRequirements: prev.specialRequirements.includes(req)
        ? prev.specialRequirements.filter(r => r !== req)
        : [...prev.specialRequirements, req]
    }));
  };

  const handleAddCharge = () => {
    if (chargeName && chargeAmount) {
      setAdvancedCharges(prev => [...prev, { name: chargeName, amount: parseFloat(chargeAmount) }]);
      setChargeName('');
      setChargeAmount('');
    }
  };

  const handleRemoveCharge = (index) => {
    setAdvancedCharges(prev => prev.filter((_, i) => i !== index));
  };

  // Additional routes handlers
  const handleAddRoute = () => {
    if (newRouteLocation && newRouteDate) {
      setAdditionalRoutes(prev => [
        ...prev,
        {
          location: newRouteLocation,
          type: newRouteType,
          date: newRouteDate
        }
      ]);
      // Reset form
      setNewRouteLocation('');
      setNewRouteType('pickup');
      setNewRouteDate('');
      setShowAddRoute(false);
    }
  };

  const handleRemoveRoute = (index) => {
    setAdditionalRoutes(prev => prev.filter((_, i) => i !== index));
  };

  // Trigger AI distance calculation when origin and destination are filled
  useEffect(() => {
    const calculateDistance = async () => {
      if (formData.origin && formData.destination && !loadId) {
        try {
          const token = await getAuthToken();
          const response = await fetch(`${API_URL}/ai/calculate-distance`, {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              'Authorization': `Bearer ${token}`
            },
            body: JSON.stringify({
              origin: formData.origin,
              destination: formData.destination
            })
          });
          
          if (response.ok) {
            const data = await response.json();
            setEstimatedDistance(data.distance_miles);
            setEstimatedTransitTime(data.estimated_hours);
            console.log('✅ Distance calculated:', data);
          }
        } catch (err) {
          console.log('Distance calculation failed:', err);
        }
      }
    };

    // Debounce the calculation
    const timer = setTimeout(calculateDistance, 1000);
    return () => clearTimeout(timer);
  }, [formData.origin, formData.destination]);

  // Auto-calculate load cost when rate per mile and distance are available
  useEffect(() => {
    if (formData.rateType === 'perMile' && estimatedDistance && formData.linehaul) {
      const ratePerMile = parseFloat(formData.linehaul);
      if (!isNaN(ratePerMile)) {
        const calculatedLinehaul = estimatedDistance * ratePerMile;
        console.log(`💰 Calculated linehaul: ${calculatedLinehaul.toFixed(2)} (${estimatedDistance} miles × $${ratePerMile}/mile)`);
      }
    }
  }, [formData.rateType, formData.linehaul, estimatedDistance]);

  const calculateTotalPay = () => {
    let linehaul = parseFloat(formData.linehaul) || 0;
    // If per-mile pricing, multiply by distance
    if (formData.rateType === 'perMile' && estimatedDistance) {
      linehaul = linehaul * estimatedDistance;
    }
    const fuelSurcharge = parseFloat(formData.fuelSurcharge) || 0;
    const advancedTotal = advancedCharges.reduce((sum, charge) => sum + parseFloat(charge.amount || 0), 0);
    return linehaul + fuelSurcharge + advancedTotal;
  };

  // Get authentication token
  const getAuthToken = async () => {
    const user = auth.currentUser;
    if (!user) throw new Error(tr('auth.notAuthenticated', 'Not authenticated'));
    return await user.getIdToken();
  };

  // Step 1: Create load with route & equipment
  const handleStep1Submit = async () => {
    setIsLoading(true);
    setError(null);
    
    try {
      const token = await getAuthToken();
      
      // Map frontend equipment names to backend enum values
      const equipmentTypeMap = {
        'Dry Van': 'Dry Van',
        'Reefer': 'Reefer',
        'Flatbed': 'Flatbed',
        'Stepdeck': 'Stepdeck',
        'Power Only': 'Power Only'
      };
      
      // Map frontend load types to backend enum values
      const loadTypeMap = {
        'FTL': 'Full Truckload',
        'LTL': 'LTL',
        'Multi-Stop': 'Multi-Stop'
      };
      
      const response = await fetch(`${API_URL}/loads/step1`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({
          origin: formData.origin,
          destination: formData.destination,
          pickup_date: formData.pickupDate,
          delivery_date: formData.deliveryDate || null,
          pickup_appointment_type: formData.pickupAppointmentType,
          delivery_appointment_type: formData.deliveryAppointmentType,
          equipment_type: equipmentTypeMap[formData.equipmentType] || 'Dry Van',
          load_type: loadTypeMap[formData.loadType] || 'Full Truckload',
          weight: parseFloat(formData.weight),
          pallet_count: formData.palletCount ? parseInt(formData.palletCount) : null,
          additional_routes: additionalRoutes  // Include additional routes
        })
      });

      if (!response.ok) {
        const errorData = await response.json();
        // Better error display for validation errors
        const errorMsg = errorData.detail 
          ? (Array.isArray(errorData.detail) 
              ? errorData.detail.map(e => `${e.loc?.join('.')}: ${e.msg}`).join(', ')
              : errorData.detail)
          : 'Failed to create load';
        throw new Error(errorMsg);
      }

      const data = await response.json();
      setLoadId(data.load_id);
      setEstimatedDistance(data.estimated_distance);
      setEstimatedTransitTime(data.estimated_transit_time);
      setStep(2); // Move to step 2
    } catch (err) {
      setError(err.message);
      console.error('Step 1 error:', err);
    } finally {
      setIsLoading(false);
    }
  };

  // Step 2: Update load with pricing & details
  const handleStep2Submit = async () => {
    if (!loadId) {
      setError(tr('addLoads.errors.loadIdNotFoundRestart', 'Load ID not found. Please restart.'));
      return;
    }
    
    setIsLoading(true);
    setError(null);
    
    try {
      const token = await getAuthToken();
      
      const rateTypeMap = {
        'flatRate': 'Flat Rate',
        'perMile': 'Per Mile',
        'hourly': 'Hourly'
      };
      
      // Calculate actual linehaul based on rate type
      let actualLinehaul = parseFloat(formData.linehaul);
      if (formData.rateType === 'perMile' && estimatedDistance) {
        actualLinehaul = estimatedDistance * parseFloat(formData.linehaul);
      }
      
      const response = await fetch(`${API_URL}/loads/${loadId}/step2`, {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({
          rate_type: rateTypeMap[formData.rateType] || 'Flat Rate',
          linehaul_rate: actualLinehaul,
          fuel_surcharge: formData.fuelSurcharge ? parseFloat(formData.fuelSurcharge) : null,
          advanced_charges: advancedCharges,
          commodity: formData.commodity || null,
          special_requirements: formData.specialRequirements,
          payment_terms: formData.paymentTerms,
          notes: formData.notes || null
        })
      });

      if (!response.ok) {
        const errorData = await response.json();
        const errorMsg = errorData.detail 
          ? (Array.isArray(errorData.detail) 
              ? errorData.detail.map(e => `${e.loc?.join('.')}: ${e.msg}`).join(', ')
              : errorData.detail)
          : 'Failed to update pricing';
        throw new Error(errorMsg);
      }

      await response.json();
      setStep(3); // Move to step 3
    } catch (err) {
      setError(err.message);
      console.error('Step 2 error:', err);
    } finally {
      setIsLoading(false);
    }
  };

  // Step 3: Finalize load with visibility & automation
  // Step 3: Just collect data, move to confirmation (Step 4)
  const handleStep3Next = () => {
    setStep(4); // No API call yet, just show confirmation
  };

  // Post load with status = ACTIVE (called from confirmation modal)
  const handlePostLoad = async () => {
    if (!loadId) {
      setError(tr('addLoads.errors.loadIdNotFoundRestart', 'Load ID not found. Please restart.'));
      return;
    }
    
    setIsLoading(true);
    setError(null);
    
    try {
      const token = await getAuthToken();
      
      const visibilityMap = {
        'public': 'Public',
        'network': 'My Network Only',
        'private': 'Selected Carriers Only'
      };

      const effectiveVisibility = isShipper ? 'public' : formData.visibility;
      
      const response = await fetch(`${API_URL}/loads/${loadId}/step3?status=ACTIVE`, {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({
          visibility: visibilityMap[effectiveVisibility] || 'Public',
          selected_carriers: isShipper ? [] : formData.selectedCarriers,
          auto_match_ai: formData.autoMatch,
          instant_booking: formData.instantBooking,
          auto_post_to_freightpower: formData.autoPostToFreightpower,
          auto_post_to_truckstop: formData.autoPostToTruckstop,
          auto_post_to_123loadboard: formData.autoPostTo123loadboard,
          notify_on_carrier_views: formData.notifyOnCarrierViews,
          notify_on_offer_received: formData.notifyOnOfferReceived,
          notify_on_load_covered: formData.notifyOnLoadCovered
        })
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.detail || tr('addLoads.errors.postFailed', 'Failed to post load'));
      }

      const data = await response.json();
      setMatchedCarriers(data.matches || []);
      onClose(); // Close modal after posting
    } catch (err) {
      setError(err.message);
      console.error('Post load error:', err);
    } finally {
      setIsLoading(false);
    }
  };

  // Save load as draft (called from confirmation modal)
  const handleSaveDraft = async () => {
    if (!loadId) {
      setError(tr('addLoads.errors.loadIdNotFoundRestart', 'Load ID not found. Please restart.'));
      return;
    }
    
    setIsLoading(true);
    setError(null);
    
    try {
      const token = await getAuthToken();
      
      const visibilityMap = {
        'public': 'Public',
        'network': 'My Network Only',
        'private': 'Selected Carriers Only'
      };

      const effectiveVisibility = isShipper ? 'public' : formData.visibility;
      
      const response = await fetch(`${API_URL}/loads/${loadId}/step3?status=DRAFT`, {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({
          visibility: visibilityMap[effectiveVisibility] || 'Public',
          selected_carriers: isShipper ? [] : formData.selectedCarriers,
          auto_match_ai: formData.autoMatch,
          instant_booking: formData.instantBooking,
          auto_post_to_freightpower: formData.autoPostToFreightpower,
          auto_post_to_truckstop: formData.autoPostToTruckstop,
          auto_post_to_123loadboard: formData.autoPostTo123loadboard,
          notify_on_carrier_views: formData.notifyOnCarrierViews,
          notify_on_offer_received: formData.notifyOnOfferReceived,
          notify_on_load_covered: formData.notifyOnLoadCovered
        })
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.detail || tr('addLoads.errors.saveDraftFailed', 'Failed to save draft'));
      }

      onClose(); // Close modal after saving
    } catch (err) {
      setError(err.message);
      console.error('Save draft error:', err);
    } finally {
      setIsLoading(false);
    }
  };

  // Generate AI driver instructions
  const handleGenerateInstructions = async () => {
    if (!loadId) return;
    
    setIsLoading(true);
    
    try {
      const token = await getAuthToken();
      
      const response = await fetch(`${API_URL}/loads/generate-instructions`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({
          load_id: loadId,
          origin: formData.origin,
          destination: formData.destination,
          equipment_type: formData.equipmentType,
          commodity: formData.commodity,
          special_requirements: formData.specialRequirements
        })
      });

      if (!response.ok) {
        throw new Error(tr('addLoads.errors.generateInstructionsFailed', 'Failed to generate instructions'));
      }

      const data = await response.json();
      setFormData(prev => ({
        ...prev,
        notes: data.instructions
      }));
    } catch (err) {
      console.error('Generate instructions error:', err);
    } finally {
      setIsLoading(false);
    }
  };

  const handleNext = () => {
    if (step === 1) {
      handleStep1Submit();
    } else if (step === 2) {
      handleStep2Submit();
    } else if (step === 3) {
      handleStep3Next(); // Just move to confirmation, don't post yet
    } else if (step < 4) {
      setStep(step + 1);
    }
  };

  const handleBack = () => {
    if (step > 1) setStep(step - 1);
  };

  const handleReviewLoad = () => {
    handleStep3Next(); // Just move to confirmation
  };

  const handleFinalPostLoad = () => {
    // Removed - using handlePostLoad now
  };

  return (
    <div className="add-loads-overlay" onClick={onClose}>
      <div className="add-loads-modal" onClick={(e) => e.stopPropagation()}>
        <button className="add-loads-close" aria-label={tr('common.close', 'Close')} onClick={onClose}>×</button>
        
        <div className="add-loads-page">
          <div className="add-loads-container">
            {/* STEP 1: Route & Equipment */}
            {step === 1 && (
              <div className="add-loads-step">
                <div className="step-header">
                  <h2>{tr('addLoads.title', 'Create New Load')}</h2>
                  <p className="step-subtitle">{tr('addLoads.step1.subtitle', 'Step 1 of 3 – Route & Equipment')}</p>
                  <p className="step-description">
                    {loadId
                      ? `${tr('addLoads.loadIdPrefix', 'Load ID:')} ${loadId}`
                      : tr('addLoads.loadIdGeneratedAfterStep1', 'Load ID generated after Step 1')}
                  </p>
                  {error && <div style={{color: 'red', marginTop: '10px'}}>{error}</div>}
                </div>

                <div className="form-section">
                  <h4 className="section-title">{tr('addLoads.sections.routeInfo.title', 'Route Information')}</h4>
                  <p className="section-desc">{tr('addLoads.sections.routeInfo.desc', 'Where the shipment is picked up and delivered')}</p>
                  
                  <div className="grid-2">
                    <div className="form-group">
                      <label>{tr('addLoads.fields.origin', 'Origin')} *</label>
                      <Geocoder
                        value={formData.origin}
                        onChange={(e) => handleInputChange({ target: { name: 'origin', value: e.target.value } })}
                        onSelect={(location) => {
                          setFormData(prev => ({ ...prev, origin: location.label }));
                        }}
                        placeholder={tr('addLoads.placeholders.location', 'City, State, Zip or Facility')}
                      />
                    </div>
                    <div className="form-group">
                      <label>{tr('addLoads.fields.destination', 'Destination')} *</label>
                      <Geocoder
                        value={formData.destination}
                        onChange={(e) => handleInputChange({ target: { name: 'destination', value: e.target.value } })}
                        onSelect={(location) => {
                          setFormData(prev => ({ ...prev, destination: location.label }));
                        }}
                        placeholder={tr('addLoads.placeholders.location', 'City, State, Zip or Facility')}
                      />
                    </div>
                  </div>

                  {/* Route Preview Map */}
                  {formData.origin && formData.destination && (
                    <div className="form-group" style={{ marginTop: '20px' }}>
                      <label>{tr('addLoads.fields.routePreview', 'Route Preview')}</label>
                      <div style={{ marginTop: '8px', border: '1px solid #e5e7eb', borderRadius: '8px', overflow: 'hidden' }}>
                        <RouteMap
                          origin={formData.origin}
                          destination={formData.destination}
                          waypoints={additionalRoutes.map(r => r.location)}
                          truckType={formData.equipmentType === 'Dry Van' ? 'dryVan' : 
                                     formData.equipmentType === 'Reefer' ? 'reefer' :
                                     formData.equipmentType === 'Flatbed' ? 'flatbed' : 'dryVan'}
                          onRouteCalculated={(data) => {
                            setRouteData(data);
                            setEstimatedDistance(data.distance_miles);
                            setEstimatedTransitTime(data.duration_hours);
                          }}
                          height="300px"
                        />
                      </div>
                    </div>
                  )}

                  <div className="grid-2" style={{ marginTop: '10px' }}>
                    <div className="form-group">
                      <label>{tr('addLoads.fields.pickupDate', 'Pickup Date')} *</label>
                      <input
                        type="date"
                        name="pickupDate"
                        value={formData.pickupDate}
                        onChange={handleInputChange}
                        min={new Date().toISOString().split('T')[0]}
                      />
                    </div>
                    <div className="form-group">
                      <label>{tr('addLoads.fields.deliveryDate', 'Delivery Date')}</label>
                      <input
                        type="date"
                        name="deliveryDate"
                        value={formData.deliveryDate}
                        onChange={handleInputChange}
                        min={new Date().toISOString().split('T')[0]}
                      />
                    </div>
                  </div>
                </div>

                <div className="form-section">
                  <h4 className="section-title">{tr('addLoads.sections.equipment.title', 'Equipment & Load Type')}</h4>
                  <p className="section-desc">{tr('addLoads.sections.equipment.desc', 'Define how this load should be handled')}</p>
                  
                  <div className="grid-2">
                    <div className="form-group">
                      <label>{tr('addLoads.fields.equipmentType', 'Equipment Type')} *</label>
                      <select
                        name="equipmentType"
                        value={formData.equipmentType}
                        onChange={handleInputChange}
                      >
                        <option value="Dry Van">{tr('addLoads.equipment.dryVan', 'Dry Van')}</option>
                        <option value="Reefer">{tr('addLoads.equipment.reefer', 'Reefer')}</option>
                        <option value="Flatbed">{tr('addLoads.equipment.flatbed', 'Flatbed')}</option>
                        <option value="Stepdeck">{tr('addLoads.equipment.stepdeck', 'Stepdeck')}</option>
                        <option value="Power Only">{tr('addLoads.equipment.powerOnly', 'Power Only')}</option>
                      </select>
                    </div>
                    <div className="form-group">
                      <label>{tr('addLoads.fields.weightLbs', 'Weight (lbs)')} *</label>
                      <input
                        type="text"
                        name="weight"
                        placeholder={tr('addLoads.placeholders.weight', 'e.g. 42,000')}
                        value={formData.weight}
                        onChange={handleInputChange}
                      />
                    </div>
                  </div>

                  <div className="form-group" style={{ marginTop: '10px' }}>
                    <label>{tr('addLoads.fields.loadType', 'Load Type')} </label>
                    <div className="load-type-selector">
                      <button
                        className={`load-type-btn ${formData.loadType === 'FTL' ? 'active' : ''}`}
                        onClick={() => handleLoadTypeSelect('FTL')}
                      >
                        <div className="btn-icon">📦</div>
                        <div className="btn-label">FTL</div>
                        <div className="btn-desc">{tr('addLoads.loadType.ftl.desc', 'Dedicated trailer, no sharing')}</div>
                      </button>
                      <button
                        className={`load-type-btn ${formData.loadType === 'LTL' ? 'active' : ''}`}
                        onClick={() => handleLoadTypeSelect('LTL')}
                      >
                        <div className="btn-icon">📫</div>
                        <div className="btn-label">LTL</div>
                        <div className="btn-desc">{tr('addLoads.loadType.ltl.desc', 'Shared space, multiple shippers')}</div>
                      </button>
                    </div>
                  </div>

                  <div className="form-group" style={{ marginTop: '10px' }}>
                    <label>{tr('addLoads.fields.palletCount', 'Pallet Count')}</label>
                    <input
                      type="text"
                      name="palletCount"
                      placeholder={tr('common.optional', 'Optional')}
                      value={formData.palletCount}
                      onChange={handleInputChange}
                    />
                  </div>

                  <div className="info-box">
                    <p>
                      <strong>{tr('addLoads.estimate.distance', 'Estimated Distance:')}</strong>{' '}
                      {estimatedDistance
                        ? `${estimatedDistance.toFixed(1)} ${tr('myCarrier.units.miles', 'miles')}`
                        : tr('addLoads.estimate.calculating', 'Calculating...')}
                    </p>
                    <p>
                      <strong>{tr('addLoads.estimate.transitTime', 'Estimated Transit Time:')}</strong>{' '}
                      {estimatedTransitTime
                        ? `${estimatedTransitTime.toFixed(1)} ${tr('addLoads.units.hours', 'hours')} (~${Math.ceil(estimatedTransitTime / 24)} ${tr('addLoads.units.days', 'days')})`
                        : tr('addLoads.estimate.calculating', 'Calculating...')}
                    </p>
                  </div>
                </div>

                {/* Additional Routes Section */}
                <div className="add-route-box">
                  <button 
                    className="add-route-btn" 
                    type="button"
                    onClick={() => setShowAddRoute(!showAddRoute)}
                  >
                    {tr('addLoads.additionalStops.addButton', '+ Add Additional Stop')}
                  </button>
                  <p className="add-route-desc">{tr('addLoads.additionalStops.desc', 'For multi-stop or complex shipments')}</p>
                  
                  {showAddRoute && (
                    <div className="additional-route-form" style={{
                      marginTop: '16px',
                      padding: '16px',
                      background: '#f8fafc',
                      borderRadius: '8px',
                      border: '1px solid #e2e8f0'
                    }}>
                      <div className="grid-3" style={{ marginBottom: '12px' }}>
                        <div className="form-group">
                          <label>{tr('addLoads.additionalStops.location', 'Location')}</label>
                          <input
                            type="text"
                            placeholder={tr('addLoads.placeholders.cityStateZip', 'City, State or ZIP')}
                            value={newRouteLocation}
                            onChange={(e) => setNewRouteLocation(e.target.value)}
                          />
                        </div>
                        <div className="form-group">
                          <label>{tr('addLoads.additionalStops.stopType', 'Stop Type')}</label>
                          <select
                            value={newRouteType}
                            onChange={(e) => setNewRouteType(e.target.value)}
                          >
                            <option value="pickup">{tr('addLoads.additionalStops.type.pickup', 'Pickup')}</option>
                            <option value="delivery">{tr('addLoads.additionalStops.type.delivery', 'Delivery')}</option>
                            <option value="stopover">{tr('addLoads.additionalStops.type.stopover', 'Stopover')}</option>
                          </select>
                        </div>
                        <div className="form-group">
                          <label>{tr('common.date', 'Date')}</label>
                          <input
                            type="date"
                            value={newRouteDate}
                            onChange={(e) => setNewRouteDate(e.target.value)}
                          />
                        </div>
                      </div>
                      <div style={{ display: 'flex', gap: '8px' }}>
                        <button 
                          className="btn small-cd" 
                          type="button"
                          onClick={handleAddRoute}
                          disabled={!newRouteLocation || !newRouteDate}
                        >
                          {tr('addLoads.additionalStops.addStop', 'Add Stop')}
                        </button>
                        <button 
                          className="btn small ghost-cd" 
                          type="button"
                          onClick={() => setShowAddRoute(false)}
                        >
                          {tr('common.cancel', 'Cancel')}
                        </button>
                      </div>
                    </div>
                  )}
                  
                  {/* Display added routes */}
                  {additionalRoutes.length > 0 && (
                    <div className="added-routes" style={{
                      marginTop: '16px',
                      padding: '12px',
                      background: '#fff',
                      borderRadius: '8px',
                      border: '1px solid #e2e8f0'
                    }}>
                      <h5 style={{ marginBottom: '12px', fontSize: '14px', fontWeight: '600' }}>
                        {tr('addLoads.additionalStops.title', 'Additional Stops')} ({additionalRoutes.length})
                      </h5>
                      {additionalRoutes.map((route, index) => (
                        <div
                          key={index}
                          style={{
                            display: 'flex',
                            justifyContent: 'space-between',
                            alignItems: 'center',
                            padding: '8px 12px',
                            marginBottom: '8px',
                            background: '#f8fafc',
                            borderRadius: '6px',
                            border: '1px solid #e2e8f0'
                          }}
                        >
                          <div>
                            <span style={{ fontWeight: '600', marginRight: '8px' }}>
                              {route.location}
                            </span>
                            <span style={{
                              padding: '2px 8px',
                              borderRadius: '4px',
                              fontSize: '12px',
                              marginRight: '8px',
                              background: route.type === 'pickup' ? '#dbeafe' : route.type === 'delivery' ? '#d1fae5' : '#fef3c7',
                              color: route.type === 'pickup' ? '#1e40af' : route.type === 'delivery' ? '#065f46' : '#92400e'
                            }}>
                              {route.type === 'pickup'
                                ? tr('addLoads.additionalStops.type.pickup', 'Pickup')
                                : route.type === 'delivery'
                                  ? tr('addLoads.additionalStops.type.delivery', 'Delivery')
                                  : tr('addLoads.additionalStops.type.stopover', 'Stopover')}
                            </span>
                            <span style={{ color: '#6b7280', fontSize: '14px' }}>
                              {route.date}
                            </span>
                          </div>
                          <button
                            type="button"
                            onClick={() => handleRemoveRoute(index)}
                            style={{
                              background: 'none',
                              border: 'none',
                              color: '#ef4444',
                              cursor: 'pointer',
                              fontSize: '18px'
                            }}
                            aria-label={tr('common.remove', 'Remove')}
                          >
                            ×
                          </button>
                        </div>
                      ))}
                    </div>
                  )}
                </div>

                {/* Multiple Pickups and Multiple Stop Options */}
                <div className="form-group" style={{ marginTop: '20px', display: 'flex', gap: '12px' }}>
                  <button
                    type="button"
                    className={`btn small-cd ${additionalRoutes.some(r => r.type === 'pickup') ? 'active' : ''}`}
                    onClick={() => {
                      if (!showAddRoute) {
                        setShowAddRoute(true)
                        setNewRouteType('pickup')
                      } else if (newRouteType !== 'pickup') {
                        setNewRouteType('pickup')
                      } else {
                        setShowAddRoute(false)
                      }
                    }}
                    style={{
                      flex: 1,
                      background: additionalRoutes.some(r => r.type === 'pickup') ? '#3b82f6' : '#f3f4f6',
                      color: additionalRoutes.some(r => r.type === 'pickup') ? 'white' : '#374151',
                      border: '1px solid #e5e7eb'
                    }}
                  >
                    <i className="fa-solid fa-truck-pickup" style={{ marginRight: '8px' }}></i>
                    {tr('addLoads.quickAdd.multiplePickups', 'Multiple Pickups')}
                  </button>
                  <button
                    type="button"
                    className={`btn small-cd ${additionalRoutes.some(r => r.type === 'delivery' || r.type === 'stopover') ? 'active' : ''}`}
                    onClick={() => {
                      if (!showAddRoute) {
                        setShowAddRoute(true)
                        setNewRouteType('delivery')
                      } else if (newRouteType !== 'delivery' && newRouteType !== 'stopover') {
                        setNewRouteType('delivery')
                      } else {
                        setShowAddRoute(false)
                      }
                    }}
                    style={{
                      flex: 1,
                      background: additionalRoutes.some(r => r.type === 'delivery' || r.type === 'stopover') ? '#3b82f6' : '#f3f4f6',
                      color: additionalRoutes.some(r => r.type === 'delivery' || r.type === 'stopover') ? 'white' : '#374151',
                      border: '1px solid #e5e7eb'
                    }}
                  >
                    <i className="fa-solid fa-route" style={{ marginRight: '8px' }}></i>
                    {tr('addLoads.quickAdd.multipleStops', 'Multiple Stops')}
                  </button>
                </div>

                <div className="step-actions">
                  <button className="btn small ghost-cd" onClick={onClose}>{tr('common.cancel', 'Cancel')}</button>
                  <button 
                    className="btn small-cd" 
                    onClick={handleNext}
                    disabled={isLoading || !formData.origin || !formData.destination || !formData.pickupDate || !formData.weight}
                  >
                    {isLoading ? tr('addLoads.actions.creating', 'Creating...') : tr('addLoads.actions.nextToStep2', 'Next → Price & Details')}
                  </button>
                </div>
              </div>
            )}

            {/* STEP 2: Price & Details */}
            {step === 2 && (
              <div className="add-loads-step">
                <div className="step-header">
                  <h2>{tr('addLoads.title', 'Create New Load')}</h2>
                  <p className="step-subtitle">{tr('addLoads.step2.subtitle', 'Step 2 of 3 – Price & Details')}</p>
                  <p className="step-description">{tr('addLoads.loadIdPrefix', 'Load ID:')} {loadId || tr('addLoads.loadIdPlaceholder', 'FP-2504-611-00123')}</p>
                </div>

                <div className="form-section">
                  <h4 className="section-title">{tr('addLoads.sections.pricingModel.title', 'Pricing Model')}</h4>
                  <p className="section-desc">{tr('addLoads.sections.pricingModel.desc', 'How carriers will be compensated for this load')}</p>
                  
                  <div className="pricing-model-selector">
                    <button
                      className={`pricing-btn ${formData.rateType === 'flatRate' ? 'active' : ''}`}
                      onClick={() => setFormData(prev => ({ ...prev, rateType: 'flatRate' }))}
                    >
                      <div className="pricing-icon">💚</div>
                      <div className="pricing-label">{tr('addLoads.rateType.flatRate', 'Flat Rate')}</div>
                      <div className="pricing-desc">{tr('addLoads.rateType.flatRate.desc', 'One total price for the load')}</div>
                    </button>
                    <button
                      className={`pricing-btn ${formData.rateType === 'perMile' ? 'active' : ''}`}
                      onClick={() => setFormData(prev => ({ ...prev, rateType: 'perMile' }))}
                    >
                      <div className="pricing-icon">📍</div>
                      <div className="pricing-label">{tr('addLoads.rateType.perMile', 'Per Mile')}</div>
                      <div className="pricing-desc">{tr('addLoads.rateType.perMile.desc', 'Calculated from total distance')}</div>
                    </button>
                    <button
                      className={`pricing-btn ${formData.rateType === 'hourly' ? 'active' : ''}`}
                      onClick={() => setFormData(prev => ({ ...prev, rateType: 'hourly' }))}
                    >
                      <div className="pricing-icon">⏰</div>
                      <div className="pricing-label">{tr('addLoads.rateType.hourly', 'Per CWT')}</div>
                      <div className="pricing-desc">{tr('addLoads.rateType.hourly.desc', 'Per hundred-weight pricing')}</div>
                    </button>
                  </div>
                </div>

                <div className="form-section">
                  {formData.rateType === 'perMile' && estimatedDistance && (
                    <div style={{
                      padding: '12px 16px',
                      background: '#f0f9ff',
                      border: '1px solid #3b82f6',
                      borderRadius: '8px',
                      marginBottom: '16px'
                    }}>
                      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                        <div>
                          <strong style={{ color: '#1e40af' }}>{tr('addLoads.estimate.total', 'Estimated Total:')}</strong>
                          <span style={{ marginLeft: '8px', color: '#6b7280' }}>
                            {estimatedDistance} {tr('myCarrier.units.miles', 'miles')} × ${formData.linehaul || '0'}/{tr('addLoads.units.mile', 'mile')}
                          </span>
                        </div>
                        <div style={{ fontSize: '20px', fontWeight: '700', color: '#1e40af' }}>
                          ${formData.linehaul ? (estimatedDistance * parseFloat(formData.linehaul)).toFixed(2) : '0.00'}
                        </div>
                      </div>
                    </div>
                  )}
                  <div className="grid-2">
                    <div className="form-group">
                      <label>
                        {tr('addLoads.fields.linehaulRate', 'Linehaul Rate ($)')} *
                        {formData.rateType === 'perMile' ? ` (${tr('addLoads.perMileSuffix', 'per mile')})` : ''}
                      </label>
                      <input
                        type="text"
                        name="linehaul"
                        placeholder={
                          formData.rateType === 'perMile'
                            ? tr('addLoads.placeholders.perMileRate', 'e.g. 2.50')
                            : tr('addLoads.placeholders.flatRateAmount', 'e.g. 2,750')
                        }
                        value={formData.linehaul}
                        onChange={handleInputChange}
                      />
                    </div>
                    <div className="form-group">
                      <label>{tr('addLoads.fields.fuelSurcharge', 'Fuel Surcharge ($)')}</label>
                      <input
                        type="text"
                        name="fuelSurcharge"
                        placeholder={tr('common.optional', 'Optional')}
                        value={formData.fuelSurcharge}
                        onChange={handleInputChange}
                      />
                    </div>
                  </div>

                  <div className="form-section">
                    <h4 className="section-title" style={{marginTop: '20px'}}>{tr('addLoads.sections.advancedCharges.title', 'Advanced Charges')}</h4>
                    <p className="section-desc">{tr('addLoads.sections.advancedCharges.desc', 'Additional charges beyond base rate (detention, layover, etc.)')}</p>
                    
                    <div className="advanced-pricing-form">
                      <div className="advanced-pricing-inputs">
                        <input
                          type="text"
                          placeholder={tr('addLoads.placeholders.chargeName', 'Charge Name (e.g. Detention, Layover)')}
                          value={chargeName}
                          onChange={(e) => setChargeName(e.target.value)}
                          className="charge-name-input"
                          style={{flex: 1}}
                        />
                        <input
                          type="number"
                          placeholder={tr('addLoads.placeholders.amountUsd', 'Amount ($)')}
                          value={chargeAmount}
                          onChange={(e) => setChargeAmount(e.target.value)}
                          className="charge-amount-input"
                          style={{width: '150px'}}
                        />
                        <button 
                          className="btn small-cd add-charge-btn"
                          onClick={handleAddCharge}
                        >
                          {tr('common.add', 'Add')}
                        </button>
                      </div>

                      {advancedCharges.length > 0 && (
                        <div className="charges-list">
                          {advancedCharges.map((charge, index) => (
                            <div key={index} className="charge-item">
                              <div className="charge-info">
                                <span className="charge-item-name">{charge.name}</span>
                                <span className="charge-amount">${parseFloat(charge.amount).toFixed(2)}</span>
                              </div>
                              <button 
                                className="charge-remove-btn"
                                onClick={() => handleRemoveCharge(index)}
                                aria-label={tr('addLoads.aria.removeCharge', 'Remove charge')}
                              >
                                ×
                              </button>
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                  </div>

                  <div className="form-section" >
                    <h4 className="section-title" style={{marginTop: '20px'}}>{tr('addLoads.sections.commodity.title', 'Commodity & Special Requirements')}</h4>
                    <p className="section-desc">{tr('addLoads.sections.commodity.desc', 'Add freight details and special handling needs')}</p>
                    
                    <div className="form-group">
                      <label>{tr('addLoads.fields.commodity', 'Commodity')}</label>
                      <input
                        type="text"
                        name="commodity"
                        placeholder={tr('addLoads.placeholders.commodity', 'e.g. Electronics, Produce, Machinery')}
                        value={formData.commodity}
                        onChange={handleInputChange}
                      />
                    </div>
                    
                    <div className="advanced-pricing-form">
                      <div className="advanced-pricing-inputs">
                        <input
                          type="text"
                          placeholder={tr('addLoads.placeholders.specialRequirement', 'Special requirement (e.g. Hazmat, Team Driver, TWIC)')}
                          value={chargeName}
                          onChange={(e) => setChargeName(e.target.value)}
                          className="charge-name-input"
                          style={{flex: 1}}
                        />
                        <button 
                          className="btn small-cd add-charge-btn"
                          onClick={handleAddCharge}
                        >
                          {tr('common.add', 'Add')}
                        </button>
                      </div>

                      {formData.specialRequirements.length > 0 && (
                        <div className="charges-list">
                          {formData.specialRequirements.map((req, index) => (
                            <div key={index} className="charge-item">
                              <div className="charge-info">
                                <span className="charge-item-name">{req}</span>
                              </div>
                              <button 
                                className="charge-remove-btn"
                                onClick={() => handleRemoveCharge(req)}
                                aria-label={tr('addLoads.aria.removeRequirement', 'Remove requirement')}
                              >
                                ×
                              </button>
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                  </div>
                </div>

                <div className="form-section">
                  <h4 className="section-title">{tr('addLoads.sections.paymentTerms.title', 'Payment Terms')}</h4>
                  <p className="section-desc">{tr('addLoads.sections.paymentTerms.desc', 'When carriers get paid after delivery')}</p>
                  
                  <select
                    name="paymentTerms"
                    value={formData.paymentTerms}
                    onChange={handleInputChange}
                    style={{width: '100%', padding: '10px', borderRadius: '8px', border: '1px solid #e5e7eb'}}
                  >
                    <option value="Quick Pay">{tr('addLoads.paymentTerms.quickPay', 'Quick Pay (1-2 days)')}</option>
                    <option value="15 Days">{tr('addLoads.paymentTerms.net15', 'Net 15')}</option>
                    <option value="30 Days">{tr('addLoads.paymentTerms.net30', 'Net 30')}</option>
                    <option value="Custom">{tr('addLoads.paymentTerms.factoring', 'Factoring Available')}</option>
                  </select>
                </div>

                <div className="form-section">
                  <h4 className="section-title">{tr('addLoads.sections.driverInstructions.title', 'Driver Instructions')}</h4>
                  <p className="section-desc">{tr('addLoads.sections.driverInstructions.desc', 'Shown to the driver after booking')}</p>
                  <button 
                    className="btn small ghost-cd" 
                    onClick={handleGenerateInstructions}
                    disabled={isLoading}
                    style={{marginBottom: '10px'}}
                  >
                    ✨ {isLoading ? tr('addLoads.actions.generating', 'Generating...') : tr('addLoads.actions.generateWithAi', 'Generate with AI')}
                  </button>
                  
                  <textarea
                    name="notes"
                    placeholder={tr('addLoads.placeholders.driverInstructions', 'Gate codes, check-in process, dock rules, contact details, safety requirements...')}
                    value={formData.notes}
                    onChange={handleInputChange}
                    className="driver-textarea"
                  />
                </div>

                <div className="estimated-total">
                  <p><strong>{tr('addLoads.estimatedTotalPay', 'Estimated Total Pay:')} {fmtMoney(calculateTotalPay())}</strong></p>
                </div>

                <div className="step-actions">
                  <button className="btn small ghost-cd" onClick={handleBack}>← {tr('common.back', 'Back')}</button>
                  <button 
                    className="btn small-cd" 
                    onClick={handleNext}
                    disabled={isLoading || !formData.linehaul}
                  >
                    {isLoading ? tr('common.saving', 'Saving...') : tr('addLoads.actions.nextToStep3', 'Next → Visibility')}
                  </button>
                </div>
              </div>
            )}

            {/* STEP 3: Visibility & Preferences */}
            {step === 3 && (
              <div className="add-loads-step">
                <div className="step-header">
                  <h2>{tr('addLoads.title', 'Create New Load')}</h2>
                  <p className="step-subtitle">{tr('addLoads.step3.subtitle', 'Step 3 of 3 – Visibility & Preferences')}</p>
                  <p className="step-description">{tr('addLoads.loadIdPrefix', 'Load ID:')} {loadId || tr('addLoads.loadIdPlaceholder', 'FP-2504-611-00123')}</p>
                  {error && <div style={{color: 'red', marginTop: '10px'}}>{error}</div>}
                </div>

                <div className="form-section">
                  <h4 className="section-title">{tr('addLoads.sections.visibility.title', 'Load Visibility')}</h4>
                  <p className="section-desc">{tr('addLoads.sections.visibility.desc', 'Choose who can see and book this load')}</p>
                  
                  <div className="visibility-selector">
                    <button
                      className={`visibility-btn ${formData.visibility === 'public' ? 'active' : ''}`}
                      onClick={() => handleVisibilitySelect('public')}
                    >
                      <div className="visibility-icon">🌐</div>
                      <div className="visibility-label">{tr('addLoads.visibility.public.label', 'Public Marketplace')}</div>
                      <div className="visibility-desc">{tr('addLoads.visibility.public.desc', 'Visible to all approved carriers')}</div>
                    </button>
                    <button
                      className={`visibility-btn ${formData.visibility === 'network' ? 'active' : ''} ${isShipper ? 'disabled' : ''}`}
                      onClick={() => handleVisibilitySelect('network')}
                      disabled={isShipper}
                      aria-disabled={isShipper}
                      title={isShipper ? tr('common.comingSoon', 'Coming soon') : undefined}
                      type="button"
                    >
                      <div className="visibility-icon">🤝</div>
                      <div className="visibility-label">{tr('addLoads.visibility.network.label', 'My Network')}</div>
                      <div className="visibility-desc">{tr('addLoads.visibility.network.desc', 'Preferred and contracted carriers')}</div>
                      {isShipper ? <div className="visibility-desc">{tr('common.comingSoon', 'Coming soon')}</div> : null}
                    </button>
                    <button
                      className={`visibility-btn ${formData.visibility === 'private' ? 'active' : ''} ${isShipper ? 'disabled' : ''}`}
                      onClick={() => handleVisibilitySelect('private')}
                      disabled={isShipper}
                      aria-disabled={isShipper}
                      title={isShipper ? tr('common.comingSoon', 'Coming soon') : undefined}
                      type="button"
                    >
                      <div className="visibility-icon">🔒</div>
                      <div className="visibility-label">{tr('addLoads.visibility.private.label', 'Private')}</div>
                      <div className="visibility-desc">{tr('addLoads.visibility.private.desc', 'Invitation only, select carriers')}</div>
                      {isShipper ? <div className="visibility-desc">{tr('common.comingSoon', 'Coming soon')}</div> : null}
                    </button>
                  </div>
                </div>

                <div className="form-section">
                  <h4 className="section-title">{tr('addLoads.sections.automation.title', 'Automation')}</h4>
                  <p className="section-desc">{tr('addLoads.sections.automation.desc', 'Speed up booking with intelligent automation.')}</p>
                  
                  <div className="automation-items">
                    <div className="automation-row">
                      <div className="automation-left">
                        <div className="automation-title">Auto Match Carriers with AI</div>
                        <div className="automation-desc">{tr('addLoads.automation.autoMatch.desc', 'Automatically suggest best fit carriers')}</div>
                      </div>
                      <label className="toggle-label">
                        <input
                          type="checkbox"
                          name="autoMatch"
                          checked={formData.autoMatch}
                          onChange={handleInputChange}
                          className="toggle-input"
                        />
                        <span className="toggle-slider"></span>
                      </label>
                    </div>

                    <div className="automation-row">
                      <div className="automation-left">
                        <div className="automation-title">Instant Booking</div>
                        <div className="automation-desc">{tr('addLoads.automation.instantBooking.desc', 'Allow carriers to book without approval')}</div>
                      </div>
                      <label className="toggle-label">
                        <input
                          type="checkbox"
                          name="instantBooking"
                          checked={formData.instantBooking}
                          onChange={handleInputChange}
                          className="toggle-input"
                        />
                        <span className="toggle-slider"></span>
                      </label>
                    </div>

                    <div className="automation-row">
                      <div className="automation-left">
                        <div className="automation-title">Post to FreightPower Network</div>
                        <div className="automation-desc">{tr('addLoads.automation.postFreightPower.desc', 'Publish to FreightPower marketplace')}</div>
                      </div>
                      <label className="toggle-label">
                        <input
                          type="checkbox"
                          name="autoPostToFreightpower"
                          checked={formData.autoPostToFreightpower}
                          onChange={handleInputChange}
                          className="toggle-input"
                        />
                        <span className="toggle-slider"></span>
                      </label>
                    </div>

                    <div className="automation-row">
                      <div className="automation-left">
                        <div className="automation-title">Post to TruckStop</div>
                        <div className="automation-desc">{tr('addLoads.automation.postTruckStop.desc', 'Publish to TruckStop.com load board')}</div>
                      </div>
                      <label className="toggle-label">
                        <input
                          type="checkbox"
                          name="autoPostToTruckstop"
                          checked={formData.autoPostToTruckstop}
                          onChange={handleInputChange}
                          className="toggle-input"
                        />
                        <span className="toggle-slider"></span>
                      </label>
                    </div>

                    <div className="automation-row">
                      <div className="automation-left">
                        <div className="automation-title">Post to 123Loadboard</div>
                        <div className="automation-desc">{tr('addLoads.automation.post123Loadboard.desc', 'Publish to 123Loadboard.com')}</div>
                      </div>
                      <label className="toggle-label">
                        <input
                          type="checkbox"
                          name="autoPostTo123loadboard"
                          checked={formData.autoPostTo123loadboard}
                          onChange={handleInputChange}
                          className="toggle-input"
                        />
                        <span className="toggle-slider"></span>
                      </label>
                    </div>
                  </div>
                </div>

                <div className="form-section">
                  <h4 className="section-title">{tr('common.notifications', 'Notifications')}</h4>
                  <p className="section-desc">{tr('addLoads.sections.notifications.desc', 'Get alerts about carrier activity')}</p>
                  
                  <div className="automation-items">
                    <div className="automation-row">
                      <div className="automation-left">
                        <div className="automation-title">Notify on Carrier Views</div>
                        <div className="automation-desc">{tr('addLoads.notifications.carrierViews.desc', 'Alert when carriers view this load')}</div>
                      </div>
                      <label className="toggle-label">
                        <input
                          type="checkbox"
                          name="notifyOnCarrierViews"
                          checked={formData.notifyOnCarrierViews}
                          onChange={handleInputChange}
                          className="toggle-input"
                        />
                        <span className="toggle-slider"></span>
                      </label>
                    </div>

                    <div className="automation-row">
                      <div className="automation-left">
                        <div className="automation-title">Notify on Offer Received</div>
                        <div className="automation-desc">{tr('addLoads.notifications.offerReceived.desc', 'Alert when carriers send booking offers')}</div>
                      </div>
                      <label className="toggle-label">
                        <input
                          type="checkbox"
                          name="notifyOnOfferReceived"
                          checked={formData.notifyOnOfferReceived}
                          onChange={handleInputChange}
                          className="toggle-input"
                        />
                        <span className="toggle-slider"></span>
                      </label>
                    </div>

                    <div className="automation-row">
                      <div className="automation-left">
                        <div className="automation-title">Notify on Load Covered</div>
                        <div className="automation-desc">{tr('addLoads.notifications.loadCovered.desc', 'Alert when load is successfully booked')}</div>
                      </div>
                      <label className="toggle-label">
                        <input
                          type="checkbox"
                          name="notifyOnLoadCovered"
                          checked={formData.notifyOnLoadCovered}
                          onChange={handleInputChange}
                          className="toggle-input"
                        />
                        <span className="toggle-slider"></span>
                      </label>
                    </div>
                  </div>
                </div>

                <div className="form-section">
                  <h4 className="section-title">{tr('addLoads.sections.aiRecommendations.title', 'AI Recommendations')}</h4>
                  <p className="section-desc">{tr('addLoads.sections.aiRecommendations.desc', 'Smart insights based on your load details')}</p>
                  
                  {matchedCarriers.length > 0 ? (
                    <div className="ai-recommendations">
                      <div className="ai-item">
                        <div className="ai-title">✅ {tr('addLoads.ai.matchedCarriersFound', 'Matched Carriers Found')}</div>
                        <div className="ai-desc">{matchedCarriers.length} {tr('addLoads.ai.carriersMatchedWithScores', 'carriers matched with scores')}</div>
                      </div>
                      {matchedCarriers.slice(0, 3).map((match, idx) => (
                        <div key={idx} className="ai-item">
                          <div className="ai-title">{tr('addLoads.ai.carrierPrefix', 'Carrier:')} {match.carrier_id}</div>
                          <div className="ai-desc">{tr('addLoads.ai.scorePrefix', 'Score:')} {(match.score * 100).toFixed(0)}% - {match.reasons?.join(', ')}</div>
                          <div className="ai-icon">🚛</div>
                        </div>
                      ))}
                    </div>
                  ) : (
                    <div className="ai-recommendations">
                      <div className="ai-item">
                        <div className="ai-title">{tr('addLoads.ai.bestTimeToPost.title', 'Best Time to Post')}</div>
                        <div className="ai-desc">{tr('addLoads.ai.bestTimeToPost.desc', 'Wednesday 10:00 AM – Max carrier engagement')}</div>
                        <div className="ai-icon">🕐</div>
                      </div>

                      <div className="ai-item">
                        <div className="ai-title">{tr('addLoads.ai.rateAnalysis.title', 'Rate Analysis')}</div>
                        <div className="ai-desc">{tr('addLoads.ai.rateAnalysis.desc', 'Current rate is competitive for this lane')}</div>
                        <div className="ai-icon">📊</div>
                      </div>

                      <div className="ai-item">
                        <div className="ai-title">{tr('addLoads.ai.matchingReady.title', 'Matching Ready')}</div>
                        <div className="ai-desc">{tr('addLoads.ai.matchingReady.desc', 'AI will find best carriers when posted')}</div>
                        <div className="ai-icon">✅</div>
                      </div>
                    </div>
                  )}
                </div>

                <div className="review-summary">
                  <h4>{tr('addLoads.reviewSummary.title', 'Review Summary')}</h4>
                  <div className="summary-grid">
                    <div className="summary-item">
                      <div className="summary-label">{tr('addLoads.reviewSummary.route', 'Route')}</div>
                      <div className="summary-value">{formData.origin} → {formData.destination}</div>
                    </div>
                    <div className="summary-item">
                      <div className="summary-label">{tr('addLoads.reviewSummary.equipment', 'Equipment')}</div>
                      <div className="summary-value">
                        {(formData.equipmentType === 'Dry Van' ? tr('addLoads.equipment.dryVan', 'Dry Van')
                          : formData.equipmentType === 'Reefer' ? tr('addLoads.equipment.reefer', 'Reefer')
                            : formData.equipmentType === 'Flatbed' ? tr('addLoads.equipment.flatbed', 'Flatbed')
                              : formData.equipmentType === 'Stepdeck' ? tr('addLoads.equipment.stepdeck', 'Stepdeck')
                                : tr('addLoads.equipment.powerOnly', 'Power Only'))}
                        {' - '}
                        {formData.loadType}
                      </div>
                    </div>
                    <div className="summary-item">
                      <div className="summary-label">{tr('addLoads.reviewSummary.totalPay', 'Total Pay')}</div>
                      <div className="summary-value">{fmtMoney(calculateTotalPay())}</div>
                    </div>
                  </div>
                  <div className="summary-notes">
                    <p>✅ {tr('addLoads.reviewSummary.readyToPost', 'Everything looks good and ready to post')}</p>
                    <p className="optional-note">{tr('addLoads.reviewSummary.editLater', 'You can edit this load later if needed')}</p>
                  </div>
                </div>

                <div className="step-actions">
                  <button className="btn small ghost-cd" onClick={handleBack}>← {tr('common.back', 'Back')}</button>
                  <button 
                    className="btn small-cd" 
                    onClick={handleReviewLoad}
                    disabled={isLoading}
                  >
                    {isLoading ? tr('addLoads.actions.processing', 'Processing...') : tr('addLoads.actions.proceedToPost', 'Proceed to Post →')}
                  </button>
                </div>
              </div>
            )}

            {/* STEP 4: Review & Confirm */}
            {step === 4 && (
              <div className="add-loads-step">
                <div className="review-confirm-header">
                  <h2>{tr('addLoads.posted.title', 'Load Successfully Posted! 🎉')}</h2>
                  <p className="load-id-text">{tr('addLoads.loadIdPrefix', 'Load ID:')} {loadId}</p>
                </div>

                <div className="success-banner">
                  <svg className="success-icon" width="20" height="20" viewBox="0 0 20 20" fill="none">
                    <circle cx="10" cy="10" r="10" fill="#10b981"/>
                    <path d="M6 10l2 2 5-5" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                  <span>
                    {tr('addLoads.posted.visibleToCarriers', 'Your load is now visible to carriers.')}{' '}
                    {matchedCarriers.length > 0 ? `${matchedCarriers.length} ${tr('addLoads.posted.carriersMatched', 'carriers matched!')}` : ''}
                  </span>
                </div>

                {matchedCarriers.length > 0 && (
                  <div className="confirm-card full-width" style={{marginBottom: '20px'}}>
                    <h3 className="confirm-card-title">🎯 {tr('addLoads.posted.aiMatchedCarriers', 'AI Matched Carriers')}</h3>
                    <p className="confirm-card-subtitle">{tr('addLoads.posted.topCarriers', 'Top carriers for this load')}</p>
                    
                    <div className="ai-recommendations">
                      {matchedCarriers.map((match, idx) => (
                        <div key={idx} className="ai-item">
                          <div className="ai-title">#{idx + 1} - {tr('addLoads.ai.carrierPrefixShort', 'Carrier')} {match.carrier_id}</div>
                          <div className="ai-desc">
                            {tr('addLoads.ai.matchScorePrefix', 'Match Score:')} {(match.score * 100).toFixed(0)}%
                            {match.reasons && ` • ${match.reasons.join(', ')}`}
                          </div>
                          <div className="ai-icon">🚛</div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                <div className="confirmation-grid">
                  {/* Route Summary */}
                  <div className="confirm-card">
                    <h3 className="confirm-card-title">{tr('addLoads.confirm.routeSummary.title', 'Route Summary')}</h3>
                    <p className="confirm-card-subtitle">{tr('addLoads.confirm.routeSummary.subtitle', 'Pickup & delivery details')}</p>
                    
                    <div className="confirm-detail-row">
                      <div className="confirm-detail-col">
                        <label className="confirm-label">{tr('addLoads.fields.origin', 'Origin')}</label>
                        <p className="confirm-value">{formData.origin || '—'}</p>
                      </div>
                      <div className="confirm-detail-col">
                        <label className="confirm-label">{tr('addLoads.fields.destination', 'Destination')}</label>
                        <p className="confirm-value">{formData.destination || '—'}</p>
                      </div>
                    </div>

                    <div className="confirm-detail-row">
                      <div className="confirm-detail-col">
                        <label className="confirm-label">{tr('addLoads.fields.pickupDate', 'Pickup Date')}</label>
                        <p className="confirm-value">{formData.pickupDate || '—'}</p>
                      </div>
                      <div className="confirm-detail-col">
                        <label className="confirm-label">{tr('addLoads.fields.deliveryDate', 'Delivery Date')}</label>
                        <p className="confirm-value">{formData.deliveryDate || '—'}</p>
                      </div>
                    </div>

                    {estimatedDistance && (
                      <div className="confirm-detail-row">
                        <div className="confirm-detail-col">
                          <label className="confirm-label">{tr('addLoads.confirm.distance', 'Distance')}</label>
                          <p className="confirm-value">{estimatedDistance} {tr('myCarrier.units.miles', 'miles')}</p>
                        </div>
                        {estimatedTransitTime && (
                          <div className="confirm-detail-col">
                            <label className="confirm-label">{tr('addLoads.confirm.transitTime', 'Transit Time')}</label>
                            <p className="confirm-value">{estimatedTransitTime} {tr('addLoads.units.hours', 'hours')}</p>
                          </div>
                        )}
                      </div>
                    )}
                  </div>

                  {/* Full Route Map */}
                  {formData.origin && formData.destination && (
                    <div className="confirm-detail-row" style={{ marginTop: '20px', gridColumn: '1 / -1' }}>
                      <div className="confirm-card" style={{ width: '100%' }}>
                        <h3 className="confirm-card-title">{tr('addLoads.confirm.routeMap.title', 'Route Map')}</h3>
                        <p className="confirm-card-subtitle">{tr('addLoads.confirm.routeMap.subtitle', 'Full route visualization')}</p>
                        <div style={{ marginTop: '12px', border: '1px solid #e5e7eb', borderRadius: '8px', overflow: 'hidden' }}>
                          <RouteMap
                            origin={formData.origin}
                            destination={formData.destination}
                            waypoints={additionalRoutes.map(r => r.location)}
                            truckType={formData.equipmentType === 'Dry Van' ? 'dryVan' : 
                                       formData.equipmentType === 'Reefer' ? 'reefer' :
                                       formData.equipmentType === 'Flatbed' ? 'flatbed' : 'dryVan'}
                            height="400px"
                          />
                        </div>
                      </div>
                    </div>
                  )}

                  {/* Pricing Summary */}
                  <div className="confirm-card">
                    <h3 className="confirm-card-title">{tr('addLoads.confirm.pricingSummary.title', 'Pricing Summary')}</h3>
                    <p className="confirm-card-subtitle">{tr('addLoads.confirm.pricingSummary.subtitle', 'Carrier compensation')}</p>
                    
                    <div className="pricing-breakdown">
                      <div className="pricing-row">
                        <span>{tr('addLoads.pricing.linehaul', 'Linehaul')}</span>
                        <span className="pricing-amount">${formData.linehaul || '0'}</span>
                      </div>
                      {formData.fuelSurcharge && (
                        <div className="pricing-row">
                          <span>{tr('addLoads.pricing.fuelSurcharge', 'Fuel Surcharge')}</span>
                          <span className="pricing-amount">${formData.fuelSurcharge}</span>
                        </div>
                      )}
                      {advancedCharges.length > 0 && advancedCharges.map((charge, idx) => (
                        <div key={idx} className="pricing-row">
                          <span>{charge.name}</span>
                          <span className="pricing-amount">${parseFloat(charge.amount).toFixed(2)}</span>
                        </div>
                      ))}
                      <div className="pricing-divider"></div>
                      <div className="pricing-row pricing-total">
                        <span>{tr('addLoads.reviewSummary.totalPay', 'Total Pay')}</span>
                        <span className="pricing-amount">{fmtMoney(calculateTotalPay())}</span>
                      </div>
                      <div className="pricing-row">
                        <span>{tr('addLoads.pricing.rateType', 'Rate Type')}</span>
                        <span className="pricing-amount">
                          {formData.rateType === 'flatRate'
                            ? tr('addLoads.rateType.flatRate', 'Flat Rate')
                            : formData.rateType === 'perMile'
                              ? tr('addLoads.rateType.perMile', 'Per Mile')
                              : tr('addLoads.rateType.hourly', 'Per CWT')}
                        </span>
                      </div>
                      <div className="pricing-row">
                        <span>{tr('addLoads.pricing.paymentTerms', 'Payment Terms')}</span>
                        <span className="pricing-amount">{formData.paymentTerms.replace('_', ' ')}</span>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Equipment & Freight */}
                <div className="confirm-card full-width">
                  <h3 className="confirm-card-title">{tr('addLoads.confirm.equipmentFreight.title', 'Equipment & Freight')}</h3>
                  <p className="confirm-card-subtitle">{tr('addLoads.confirm.equipmentFreight.subtitle', 'Load configuration')}</p>
                  
                  <div className="confirm-detail-row">
                    <div className="confirm-detail-col">
                      <label className="confirm-label">{tr('addLoads.reviewSummary.equipment', 'Equipment')}</label>
                      <p className="confirm-value">
                        {(formData.equipmentType === 'Dry Van' ? tr('addLoads.equipment.dryVan', 'Dry Van')
                          : formData.equipmentType === 'Reefer' ? tr('addLoads.equipment.reefer', 'Reefer')
                            : formData.equipmentType === 'Flatbed' ? tr('addLoads.equipment.flatbed', 'Flatbed')
                              : formData.equipmentType === 'Stepdeck' ? tr('addLoads.equipment.stepdeck', 'Stepdeck')
                                : tr('addLoads.equipment.powerOnly', 'Power Only'))}
                        {' - '}
                        {formData.loadType}
                      </p>
                    </div>
                    <div className="confirm-detail-col">
                      <label className="confirm-label">{tr('addLoads.confirm.weight', 'Weight')}</label>
                      <p className="confirm-value">{formData.weight ? `${formData.weight} ${tr('common.lbs', 'lbs')}` : '—'}</p>
                    </div>
                    {formData.palletCount && (
                      <div className="confirm-detail-col">
                        <label className="confirm-label">{tr('addLoads.confirm.pallets', 'Pallets')}</label>
                        <p className="confirm-value">{formData.palletCount}</p>
                      </div>
                    )}
                  </div>

                  {formData.commodity && (
                    <div className="confirm-detail-row">
                      <div className="confirm-detail-col">
                        <label className="confirm-label">{tr('addLoads.fields.commodity', 'Commodity')}</label>
                        <p className="confirm-value">{formData.commodity}</p>
                      </div>
                    </div>
                  )}

                  {formData.specialRequirements.length > 0 && (
                    <div className="confirm-detail-row">
                      <div className="confirm-detail-col">
                        <label className="confirm-label">{tr('addLoads.confirm.specialRequirements', 'Special Requirements')}</label>
                        <div className="posting-tags">
                          {formData.specialRequirements.map((req, idx) => (
                            <span key={idx} className="posting-tag">{req}</span>
                          ))}
                        </div>
                      </div>
                    </div>
                  )}
                </div>

                {/* Posting & Booking */}
                <div className="confirm-card full-width" style={{marginTop: '20px'}}>
                  <h3 className="confirm-card-title">{tr('addLoads.confirm.postingAutomation.title', 'Posting & Automation')}</h3>
                  <p className="confirm-card-subtitle">{tr('addLoads.confirm.postingAutomation.subtitle', 'Visibility & automation settings')}</p>
                  
                  <div className="posting-tags">
                    <span className="posting-tag">
                      {formData.visibility === 'public'
                        ? `🌐 ${tr('addLoads.visibility.public.label', 'Public Marketplace')}`
                        : formData.visibility === 'network'
                          ? `🤝 ${tr('addLoads.visibility.network.label', 'My Network')}`
                          : `🔒 ${tr('addLoads.visibility.private.label', 'Private')}`}
                    </span>
                    {formData.autoMatch && (
                      <span className="posting-tag">🤖 {tr('addLoads.tags.autoMatch', 'Auto-Match AI')}</span>
                    )}
                    {formData.instantBooking && (
                      <span className="posting-tag">⚡ {tr('addLoads.tags.instantBooking', 'Instant Booking')}</span>
                    )}
                    {formData.autoPostToFreightpower && (
                      <span className="posting-tag">✅ {tr('addLoads.tags.freightPower', 'FreightPower')}</span>
                    )}
                    {formData.autoPostToTruckstop && (
                      <span className="posting-tag">✅ {tr('addLoads.tags.truckStop', 'TruckStop')}</span>
                    )}
                    {formData.autoPostTo123loadboard && (
                      <span className="posting-tag">✅ {tr('addLoads.tags.loadboard123', '123Loadboard')}</span>
                    )}
                  </div>
                  
                  <div style={{marginTop: '15px'}}>
                    <p style={{fontSize: '14px', color: '#6b7280'}}>
                      📬 {tr('addLoads.notifications.enabledForPrefix', 'Notifications enabled for:')}
                      {formData.notifyOnCarrierViews && ` ${tr('addLoads.notifications.enabledFor.carrierViews', 'Carrier Views')}`}
                      {formData.notifyOnOfferReceived && ` • ${tr('addLoads.notifications.enabledFor.offersReceived', 'Offers Received')}`}
                      {formData.notifyOnLoadCovered && ` • ${tr('addLoads.notifications.enabledFor.loadCovered', 'Load Covered')}`}
                    </p>
                  </div>
                </div>

                {/* Driver Instructions */}
                {formData.notes && (
                  <div className="confirm-card full-width" style={{marginTop: '20px'}}>
                    <h3 className="confirm-card-title">{tr('addLoads.sections.driverInstructions.title', 'Driver Instructions')}</h3>
                    <p className="confirm-card-subtitle">{tr('addLoads.confirm.driverInstructions.visibleAfterBooking', 'Visible to carrier after booking')}</p>
                    
                    <p className="driver-instructions-text">
                      {formData.notes}
                    </p>
                  </div>
                )}

                <div className="confirm-actions">
                  {!isShipper && (
                    <button 
                      className="btn ghost-cd" 
                      onClick={handleSaveDraft}
                      disabled={isLoading}
                      style={{marginRight: '12px'}}
                    >
                      {isLoading ? tr('common.saving', 'Saving...') : `💾 ${tr('addLoads.actions.saveDraft', 'Save Draft')}`}
                    </button>
                  )}
                  <button 
                    className="btn small-cd" 
                    onClick={handlePostLoad}
                    disabled={isLoading}
                  >
                    {isLoading ? tr('addLoads.actions.posting', 'Posting...') : `✓ ${tr('addLoads.actions.postLoad', 'Post Load')}`}
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}